name: Create Pull Request
on:
  push:
    branches:
      - master
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node_version: 12
          registry-url: 'https://npm.pkg.github.com'
      - name: Set Current CHANGELOG to output
        id: changelog
        run: |
          version=$(node -p 'require("./lerna.json").version')
          output=$(./node_modules/.bin/monorepo-utils-collect-changelog --changelog ./CHANGELOG.md `node -p 'require("./lerna.json").version'`)
          echo "::set-output name=changelog::${output}"
          echo "::set-output name=version::${version}"
      - name: Versionup commit
        run: |
          yarn run versionup --yes
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update v${{ steps.changelog.outputs.version }}"
          committer: GitHub <noreply@github.com>
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          title: 'v${{ steps.changelog.outputs.version }}'
          body: |
            ${{ steps.changelog.outputs.changelog }}
          labels: "Type: Release"
          branch: example-patches
          request-to-parent: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
