name: test
on: [push, pull_request]
env:
  CI: true
jobs:
  test:
    name: "Test on Node.js"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: 12
      - name: Install
        run: yarn install
      - name: Version up
        run: |
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          yarn version $CURRENT_VERSION
